version: '3.5'

services:
  web:
    stdin_open: true
    tty: true
    shm_size: '256mb'
    tmpfs:
      - /tmp
    env_file:
      - ./docker/env/rails.env
    build:
      context: .
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - PROJECT_FOLDER=${PROJECT_FOLDER:-colabora}
    volumes:
      - .:/colabora
      - ./docker/rails/bundle:/usr/local/bundle
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
    networks:
      colabora_network:

  postgres:
    stdin_open: true
    tty: true
    image: postgres:13
    shm_size: '1gb'
    env_file:
      - ./docker/env/postgres.env
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data
      - ./docker/postgresql/dumps:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    networks:
      colabora_network:

  redis:
    image: redis:alpine
    stdin_open: true
    tty: true
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis/data:/data
    networks:
      colabora_network:

volumes:
  web:
  postgres:
  redis:

networks:
  colabora_network:
    name: colabora_network
